version: "3"
services:
  go:
    container_name: golang
    restart: always
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env  
    volumes:
      - .:/usr/src/goApp

#volumes:
    #Golang:
       #external: true        
