import Head from 'next/head';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Fase 4</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex items-center justify-center h-screen">
                
                <div className="min-h-screen hero bg-base-200">
                    <div className="text-center hero-content">
                        <div className="max-w-md">
                            <h1 className="text-4xl font-bold">
                                MetaOS - Fase 4
                            </h1>

                            {/* <p className="py-6">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p> */}
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}
